// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0MOhvnUNxmsxqVBc9PXRBa4m4LIMw6vc',
    appId: '1:517224872131:web:1afd9015054b165fdf8a76',
    messagingSenderId: '517224872131',
    projectId: 'classroom-mejorado',
    authDomain: 'classroom-mejorado.firebaseapp.com',
    storageBucket: 'classroom-mejorado.firebasestorage.app',
    measurementId: 'G-T9YRY12WY6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPvPj8f4RhOVou_fpmKYIcuyDXiR2u9WM',
    appId: '1:517224872131:android:bb246b8e71f796cedf8a76',
    messagingSenderId: '517224872131',
    projectId: 'classroom-mejorado',
    storageBucket: 'classroom-mejorado.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCA2Y7OIbd6LVaLBhq6rLSGttsjmoUBnUY',
    appId: '1:517224872131:ios:a491bc02ed58a194df8a76',
    messagingSenderId: '517224872131',
    projectId: 'classroom-mejorado',
    storageBucket: 'classroom-mejorado.firebasestorage.app',
    iosClientId: '517224872131-bkrfb9ct7lsjlauk1lckvh4mg5q8sbdo.apps.googleusercontent.com',
    iosBundleId: 'com.example.classroomMejorado',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCA2Y7OIbd6LVaLBhq6rLSGttsjmoUBnUY',
    appId: '1:517224872131:ios:a491bc02ed58a194df8a76',
    messagingSenderId: '517224872131',
    projectId: 'classroom-mejorado',
    storageBucket: 'classroom-mejorado.firebasestorage.app',
    iosClientId: '517224872131-bkrfb9ct7lsjlauk1lckvh4mg5q8sbdo.apps.googleusercontent.com',
    iosBundleId: 'com.example.classroomMejorado',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0MOhvnUNxmsxqVBc9PXRBa4m4LIMw6vc',
    appId: '1:517224872131:web:c1ff423f39bb3760df8a76',
    messagingSenderId: '517224872131',
    projectId: 'classroom-mejorado',
    authDomain: 'classroom-mejorado.firebaseapp.com',
    storageBucket: 'classroom-mejorado.firebasestorage.app',
    measurementId: 'G-D7LX4R7T17',
  );
}
